### PR TITLE
fix nil pointer crash

### PR DESCRIPTION
**Pull request by elcritch**

### CODE REVIEW

**Comment by guzba** [comment]
Hi, could you add a little more info to this issue, maybe how it came up or how to reproduce it?

It is not valid to have a Typeface that is not nil and does not have an otf or svg font internally. It seems this is attempting to fix an issue caused by invalid state, and not a situation I'd want to be extensively supporting or testing going forward.

**Comment by elcritch** [comment]
> It is not valid to have a Typeface that is not nil and does not have an otf or svg font internally. It seems this is attempting to fix an issue caused by invalid state, and not a situation I'd want to be extensively supporting or testing going forward.

That makes sense, it's definitely bad state from my app.

However I wasn't sure if there were scenarios where you could end up calling `hasGlyph` without having valid svgFont or opentype loaded yet. In that case returning false, or perhaps better raising a defect could be useful. 

But yah if it's not possible to end up in that state by normal usage then it'd not make sense to guard it here.

> Hi, could you add a little more info to this issue, maybe how it came up or how to reproduce it?

It's hard to reproduce. I'm using Pixie from two different threads but with different data. It seems like they should be independent of each other. From what code I've seen and the stacktrace I'm not sure how it's possible for them to affect each other so that I can properly isolate them / protect them.

Ideally I'd like to use be able to use pixie to render things from different threads, but I could keep move it to a single thread or put a lock around the usage, etc. However I don't know if there's any shared globals or something that'd lead to this invalid state. 

Oddly, with this patch it runs fine for 12+ hours and as far as I can tell Pixie creates the proper glyphs and text renderings every time. Before it was crashing every ~20-30 minutes.

P.S. There's also a chance it's somewhere else in Pixie. I've found that the 2.0 release has cases where it's stacktraces aren't correct. That's fun, and I'll try to reproduce this in a debugger to verify this is the location.

**Comment by guzba** [comment]
> raising a defect could be useful.

I don't really disagree per-se, but there are many ways for a nil deref crash to happen and picking just this specific one and making it a Defect is a bit "why just this one?".

deally I'd like to use be able to use pixie to render things from different threads, but I could keep move it to a single thread or put a lock around the usage, etc. However I don't know if there's any shared globals or something that'd lead to this invalid state.

FYI that this is dangerous and going to cause strange issues if not done carefully. Most objects in Pixie are `ref object` which cannot be used across threads under almost any circumstances (see the atomic arc discussion).

> I've found that the 2.0 release has cases where it's stacktraces aren't correct. That's fun, and I'll try to reproduce this in a debugger to verify this is the location.

If 2.0 has flaky locations I suggest reproducing in 1.6.x. It appears 2.0 has some allocator / memory / destructor issues so I would not be using it production until that is sorted out in a future release.

**Comment by elcritch** [comment]
Ok I dug in with a debugger and figured out that I appear to be getting an empty font object occasionally. That's likely due to threading issues / race conditions in my code or 2.0 shenanigans as you pointed out. 

However, it looks like passing an improperly initialized `Font` object causes Pixie to fail with the same NPE immediately. Having a guard for this scenario would probably help users who use the API incorrectly by accident as it looks innocent enough. 

Here's the modified code that segfaults every time:

```nim
proc getTypeset*(text: string, font: FontId, box: Box): GlyphArrangement =
  let
    rect = box.scaled()
    wh = rect.wh
    # pf = fontTable[font]
  var pf = Font() # empty font 
  let
    arrangement = typeset(@[newSpan(text, pf)], bounds = rect.wh)
```

Here's the debugger output:

```c
(tyObject_TypefacecolonObjectType___hnGWBKtOaU9ciF2FG6z7raQ) $7 = {
  opentype = NULL
  svgFont = NULL
  filePath = {
    len = 0
    p = NULL
  }
  fallbacks = {
    len = 0
    p = NULL
  }
}
```

**Comment by guzba** [comment]
Just making a Font is again not supported. This is why readFont, newFont etc exist, to great objects in valid states. I am not aware of any way to stop `Font()` from compiling, but that is the only valid solution I can see. I don't think going through the exercise of making every single possible allocation type not segfault in every library is a productive way to spend time.

**Comment by elcritch** [comment]
> Just making a Font is again not supported. This is why readFont, newFont etc exist, to create objects in valid states. I am not aware of any way to stop Font() from compiling, but that is the only valid solution I can see. 

You could throw an exception if the font's not initialized properly or do the nil check like this PR.

> I don't think going through the exercise of making every single possible allocation type not segfault in every library is a productive way to spend time.

Well personally I'd disagree and prefer to detect cases where it's easy to misuse an external API. Especially for new users, it's easy to do `var font = Font()` by accident, forgetting, or not reading the docs or fail to understand why it's bad. But it's your library, just adding a suggestion. :)

> FYI that this is dangerous and going to cause strange issues if not done carefully. Most objects in Pixie are ref object which cannot be used across threads under almost any circumstances (see the atomic arc discussion).

Yah, I need to make sure these Font objects aren't shared or locked. I pass a `FontId` around for that reasons, but looks like I forgot this case with the table.

**Comment by guzba** [comment]
There are at least 15+ locations that would need nil-check-to-Defect code just for Font. Add Image, Path, Typeface, Context etc and its a huge amount of work and maintenance for all future code.

The real deal here is that Nim does not check for nil, instead it just segfaults. This is the root decision it appears to me that you're disagreeing with. There is https://nim-lang.org/docs/segfaults.html to change this behavior. Should work for all code in all libraries with no `== nil: raise` code littered all over the place.

**Comment by elcritch** [comment]
> There are at least 15+ locations that would need nil-check-to-Defect code just for Font. Add Image, Path, Typeface, Context etc and its a huge amount of work and maintenance for all future code.

That's a fair point. I just found this one and can't weigh the overhead for all of the other places. I like to add a `font.checkValid()` on public facing APIs with similar cases or use a `font.fontType()` getter proc that'd also check the font. Scattering nil checks all over internally would be a pain! :/ 

> The real deal here is that Nim does not check for nil, instead it just segfaults. This is the root decision it appears to me that you're disagreeing with. 

True I'd forgotten about that guy, might be a good idea. My general habit from C++ days is to try and add those nil checks on public API's when I can and still do it since Nim's default is to not catch NPEs. At least Nim produces a stacktrace which usually makes it easy to fix.

And Pixie is fantastic! I get your decisions if it's too much API space, overhead etc. I just like to try and help "harden" certain API's if possible since usually if I run into it, someone else has too.

Thanks again for the fantastic library! Probably can close this issue?

**Comment by guzba** [comment]
I am very open to the argument that, unless `-d:danger` is specified, Nim should be doing nil checks and raising NilDefect instead of segfaulting so I feel you on the pain here. Not a choice that can be changed now though and it isn't a choice without trade-offs anyway.

I am not eager to go through all of Pixie and add nil checks. It's not like it would be a bad idea, its just not a way I would personally enjoy spending time when I have other things I'd rather be doing that are far more interesting. I get that it could improve the lib for new users, but in the end, one does need to learn how to use a library correctly in order to do anything productively with it anyway, and the nil issue will just surface in other places so I'm not confident it would be a significant net win across the net of a project using Pixie. Hard to say, and in the end, its mostly down to being uninteresting work to do.

I am not 100% sure we don't have a bug here, re: the original issue. Only have what has been reported to go on. I would say if you can confirm that the issue is either threading-related or an unsupported usage issue that is fixed outside of Pixie, then all is good.

**Comment by elcritch** [comment]
> I am not eager to go through all of Pixie and add nil checks. It's not like it would be a bad idea, its just not a way I would personally enjoy spending time when I have other things I'd rather be doing that are far more interesting. 

I totally get that! And I wouldn't think it'd be that fruitful either to do the whole thing. Hopefully you didn't take it as my recommendation either. This one case just seemed useful on it's own to me since checking if there's one font or another is gonna be fairly central. And I wasn't sure if it was some deeper issue or not. 

> I get that it could improve the lib for new users, but in the end, one does need to learn how to use a library correctly in order to do anything productively with it anyway, and the nil issue will just surface in other places so I'm not confident it would be a significant net win across the net of a project using Pixie. Hard to say, and in the end, its mostly down to being uninteresting work to do.

Definitely, that makes sense. I mean having it in the GitHub project history is useful too if others do something similar. 

> I am not 100% sure we don't have a bug here, re: the original issue. Only have what has been reported to go on. I would say if you can confirm that the issue is either threading-related or an unsupported usage issue that is fixed outside of Pixie, then all is good.

Yah, I can confirm the issue in my code arose from a threading issue where an "empty" font object was being returned sometimes. Tracking it down wasn't hard once I understood the font object a bit better. The font itself wasn't nil, which confused me. 

I appreciate the conversation and your feedback. It was helpful!

**Pull request closed without merging**
