### PR TITLE
The great enum rename.

### PR DESCRIPTION
**Pull request by treeform**

### CODE REVIEW

**Comment by AmjadHD** [comment]
What's the point of this change ?

> Unless marked with the `{.pure.}` pragma, members of enums should have an identifying prefix, such as an abbreviation of the enum's name.
> 
> ```nim
> type
>   PathComponent = enum
>     pcDir
>     pcLinkToDir
>     pcFile
>     pcLinkToFile
> ```
> 
> Non-pure enum values should use camelCase whereas pure enum values should use PascalCase.
> 
> ```nim
> type
>   PathComponent {.pure.} = enum
>     Dir
>     LinkToDir
>     File
>     LinkToFile
> ```

**Comment by SolitudeSF** [comment]
that styleguide entry was written before there was enum overloading

**Comment by treeform** [comment]
Enum overloading is the new thing in experimental, which in my mind removes {.pure.} enums and makes all enums behave how you would expect without the need for the strange name prefix. And this is the experimental branch using this feature.

**Comment by treeform** [comment]
Doing a different PR now.

**Pull request closed without merging**
