### PR TITLE
fix pixie for https://github.com/nim-lang/Nim/pull/18050

### PR DESCRIPTION
**Pull request by timotheecour**
unblocks https://github.com/nim-lang/Nim/pull/18050 which fixes the long-standing generic sandwich problem in nim

this is forward and backward compatible.

### CODE REVIEW

**Comment by treeform** [comment]
I am not sure what is going on here? We can't write `values.rgbx()` any more once that PR goes in and must always write `rgbx(values)` ?

**Comment by timotheecour** [comment]
in most cases you can still use MCS, but in this case you'll need either mixin or avoid MCS, due to https://nim-lang.org/docs/manual.html#templates-limitations-of-the-method-call-syntax

**Comment by guzba** [comment]
MCS = method call syntax, and this looks like a template limitation that I've not been aware of. It appears to be very specific to this area where rgbx is actually a template, not the rgbx proc from chroma used very often elsewhere in pixie.

Thanks for the PR @timotheecour and for the quick explanation to get us on the right track to learn more.

**Comment by treeform** [comment]
Thank you for the PR, merging!

**Pull request merged**
